[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
[project]
name="test_scm"
# version = "0.0.1"  # Remove any existing version parameter.
dynamic = ["version"]
[tool.setuptools_scm]